"""Generate `setup-tier1.sh` — a reviewable, idempotent shell script that
enables Tier 1 IAM Principal Cost Tracking for the audited account.

Design principles:
  - Customer reviews before running. We never auto-execute.
  - Every command commented with what it does and what it changes.
  - Idempotency checks where possible (e.g., skip tag-role if tag already
    has the suggested value).
  - --dry-run as the default by way of placeholders the customer must edit
    (TAG_VALUE_TO_REVIEW etc.) — forces them to make a deliberate decision.
  - Generated script is bash-compatible (`set -euo pipefail`) and uses only
    `aws` CLI — no jq, python, or other shell dependencies.

The script has three sections:
  1. Tag IAM principals — applies tag suggestions from taxonomy.py
  2. Activate cost allocation tags — Billing console action (CLI commands
     for `aws ce update-cost-allocation-tags-status`)
  3. Create CUR 2.0 export — `bcm-data-exports create-export` with caller
     identity included

Section 2 + 3 only fire when run from the Organizations management
account, since member accounts can't activate cost allocation tags.
"""
from __future__ import annotations

import datetime
from pathlib import Path

from core.models import AccountFindings
from core.taxonomy import TagSuggestion


# Header — explains what this is, when it was generated, and big warnings.
SCRIPT_HEADER_TEMPLATE = """#!/usr/bin/env bash
#
# setup-tier1.sh — Bedrock IAM Principal Cost Tracking enablement
#
# Generated by bedrock-attribution-audit on {generated_at}
# For account: {account_id} ({account_name})
# Audit run:   {audit_started_at}
#
# ════════════════════════════════════════════════════════════════════
#  ⚠  REVIEW EVERY COMMAND BEFORE RUNNING THIS SCRIPT  ⚠
# ════════════════════════════════════════════════════════════════════
#
# This script makes WRITES to your AWS account:
#   - Sets IAM tags on roles (Section 1)
#   - Activates cost allocation tags (Section 2 — management account only)
#   - Creates a CUR 2.0 data export (Section 3 — management account only)
#
# The bedrock-attribution-audit tool is read-only. THIS script is not.
#
# Usage:
#   1. Open this file in an editor.
#   2. Replace every TAG_VALUE_TO_REVIEW placeholder with your actual
#      tag values OR delete the line if you don't want that tag.
#   3. Update AWS_PROFILE / AWS_REGION at the top if needed.
#   4. Read each section and decide what you want to run.
#   5. Run with: bash setup-tier1.sh
#      (Or copy-paste individual commands one at a time.)
#
# Rollback:
#   - IAM tag changes: re-run with the prior values, or use
#     `aws iam untag-role --role-name <name> --tag-keys <key>`.
#   - Cost allocation tag activation: deactivate via
#     `aws ce update-cost-allocation-tags-status --status Inactive ...`
#   - CUR 2.0 export: delete via
#     `aws bcm-data-exports delete-export --export-arn <arn>`.
#

set -euo pipefail

# ───────── CONFIGURATION ─────────
AWS_PROFILE="${{AWS_PROFILE:-default}}"
AWS_REGION="${{AWS_REGION:-us-east-1}}"

echo "Using profile: $AWS_PROFILE"
echo "Using region:  $AWS_REGION"
echo
echo "⚠  This script will make writes to AWS. Press Ctrl-C now to abort."
sleep 5
echo
"""


def _format_tag_args(tags: dict[str, str]) -> str:
    """Render tags for `aws iam tag-role --tags Key=k,Value=v ...`."""
    if not tags:
        return ""
    return " ".join(f"Key={k},Value={v}" for k, v in sorted(tags.items()))


def _section_tag_iam_principals(
    findings: AccountFindings, suggestions: list[TagSuggestion]
) -> str:
    """Section 1: tag IAM principals using taxonomy suggestions."""
    if not suggestions:
        return (
            "# ════════════════════════════════════════════════════════════════════\n"
            "# Section 1: Tag IAM principals\n"
            "# ════════════════════════════════════════════════════════════════════\n"
            "# (Skipped — no Bedrock-capable principals were detected in this account.)\n\n"
        )

    out = [
        "# ════════════════════════════════════════════════════════════════════",
        "# Section 1: Tag Bedrock-capable IAM principals",
        "# ════════════════════════════════════════════════════════════════════",
        "#",
        f"# {len(suggestions)} principal(s) detected in this account. Each block below",
        "# applies the taxonomy suggested in suggested-tags.csv. Review and edit",
        "# the values before running. Lines marked TAG_VALUE_TO_REVIEW must be",
        "# replaced with a real value (or the entire line deleted).",
        "#",
    ]

    for s in suggestions:
        confidence_marker = {"high": "", "medium": "  # confidence: medium", "low": "  # confidence: LOW — review carefully"}[
            s.confidence
        ]
        # Replace any "REVIEW" placeholder with a clearer placeholder sentinel.
        cleaned_tags = {
            k: ("TAG_VALUE_TO_REVIEW" if v == "REVIEW" else v)
            for k, v in s.suggested_tags.items()
        }

        # Identity Center roles can't be tagged via iam:TagRole — they live
        # under aws-reserved and are managed by IAM Identity Center. Skip
        # with a comment.
        if "/aws-reserved/sso." in s.arn:
            out.append(f"# {s.name}: Identity Center role — tagging via iam:TagRole is not supported.")
            out.append(f"#   To tag, edit the permission set in IAM Identity Center.")
            out.append(f"#   Suggestion (apply via Identity Center): {cleaned_tags}")
            out.append("")
            continue

        out.append(f"# {s.name}{confidence_marker}")
        out.append(f"#   Reasoning: {s.reasoning}")
        is_user = ":user/" in s.arn
        cmd_verb = "tag-user" if is_user else "tag-role"
        name_flag = "--user-name" if is_user else "--role-name"
        out.append(
            f'aws iam {cmd_verb} {name_flag} "{s.name}" \\'
        )
        out.append(f'    --tags {_format_tag_args(cleaned_tags)} \\')
        out.append(f'    --profile "$AWS_PROFILE"')
        out.append("")

    out.append("")
    return "\n".join(out)


def _section_activate_cost_allocation_tags(findings: AccountFindings) -> str:
    """Section 2: activate cost allocation tags (management account only)."""
    if not findings.is_management_account:
        return (
            "# ════════════════════════════════════════════════════════════════════\n"
            "# Section 2: Activate cost allocation tags\n"
            "# ════════════════════════════════════════════════════════════════════\n"
            "# (Skipped — only the Organizations management account can activate\n"
            "# cost allocation tags. Run setup-tier1.sh from the management account.)\n\n"
        )

    return """# ════════════════════════════════════════════════════════════════════
# Section 2: Activate IAM principal cost allocation tags
# ════════════════════════════════════════════════════════════════════
#
# Tag activation is a one-time operation. After activation, AWS Billing
# starts including these tags in CUR 2.0 and Cost Explorer with the
# `iamPrincipal/` prefix (e.g., iamPrincipal/team).
#
# Tags only appear in the Billing console for activation AFTER the IAM
# principal carrying that tag has made at least one Bedrock API call.
# If the tags below aren't in the Billing console yet, run a few Bedrock
# calls from those tagged principals first, wait 24h, then re-run this.
#
# This must be run from the Organizations management account.

# Activate the tags we expect to use for attribution. Edit this list to
# match the dimensions you actually applied in Section 1.
for TAG_KEY in team cost-center environment project; do
    echo "Activating cost allocation tag: iamPrincipal/${TAG_KEY}"
    aws ce update-cost-allocation-tags-status \\
        --cost-allocation-tags-status TagKey="iamPrincipal/${TAG_KEY}",Status=Active \\
        --profile "$AWS_PROFILE" || \\
        echo "  (Tag iamPrincipal/${TAG_KEY} may not have flowed to Billing yet — that's OK, retry later)"
done

"""


def _section_create_cur_export(findings: AccountFindings) -> str:
    """Section 3: create the CUR 2.0 export with caller identity."""
    if not findings.is_management_account:
        return (
            "# ════════════════════════════════════════════════════════════════════\n"
            "# Section 3: Create CUR 2.0 export with IAM principal data\n"
            "# ════════════════════════════════════════════════════════════════════\n"
            "# (Skipped — CUR 2.0 exports are managed at the management account.)\n\n"
        )

    if findings.iam_principal_cost_tracking_likely_enabled:
        return (
            "# ════════════════════════════════════════════════════════════════════\n"
            "# Section 3: Create CUR 2.0 export with IAM principal data\n"
            "# ════════════════════════════════════════════════════════════════════\n"
            "# (Skipped — an existing CUR 2.0 export with IAM principal data was\n"
            "# already detected during the audit. No new export required.)\n\n"
        )

    # Use the account ID in the bucket name to make collisions less likely
    suggested_bucket = f"bedrock-cur2-export-{findings.account_id}"

    return f"""# ════════════════════════════════════════════════════════════════════
# Section 3: Create CUR 2.0 export with IAM principal data
# ════════════════════════════════════════════════════════════════════
#
# This creates a fresh CUR 2.0 data export that includes the
# `line_item_iam_principal` column. Existing CUR exports are NOT
# retroactively patched — a new export is required.
#
# Step 3a. Create the destination S3 bucket. Skip if you already have
# a CUR-destination bucket you want to reuse.

CUR_BUCKET_NAME="{suggested_bucket}"
CUR_BUCKET_REGION="us-east-1"   # CUR 2.0 is currently us-east-1 only

if ! aws s3api head-bucket --bucket "$CUR_BUCKET_NAME" --profile "$AWS_PROFILE" 2>/dev/null; then
    echo "Creating bucket: $CUR_BUCKET_NAME"
    aws s3api create-bucket \\
        --bucket "$CUR_BUCKET_NAME" \\
        --region "$CUR_BUCKET_REGION" \\
        --profile "$AWS_PROFILE"
    aws s3api put-bucket-policy \\
        --bucket "$CUR_BUCKET_NAME" \\
        --profile "$AWS_PROFILE" \\
        --policy '{{
            "Version": "2012-10-17",
            "Statement": [
                {{
                    "Sid": "AllowBillingService",
                    "Effect": "Allow",
                    "Principal": {{ "Service": "billingreports.amazonaws.com" }},
                    "Action": ["s3:GetBucketAcl", "s3:GetBucketPolicy"],
                    "Resource": "arn:aws:s3:::'"$CUR_BUCKET_NAME"'"
                }},
                {{
                    "Sid": "AllowBillingServiceWrite",
                    "Effect": "Allow",
                    "Principal": {{ "Service": "billingreports.amazonaws.com" }},
                    "Action": "s3:PutObject",
                    "Resource": "arn:aws:s3:::'"$CUR_BUCKET_NAME"'/*"
                }}
            ]
        }}'
fi

# Step 3b. Create the CUR 2.0 export.
echo "Creating CUR 2.0 export with IAM principal data..."
aws bcm-data-exports create-export \\
    --profile "$AWS_PROFILE" \\
    --region "$CUR_BUCKET_REGION" \\
    --export '{{
        "Name": "bedrock-cur2-with-iam-principal",
        "Description": "CUR 2.0 export with line_item_iam_principal — generated by bedrock-attribution-audit",
        "DataQuery": {{
            "QueryStatement": "SELECT * FROM COST_AND_USAGE_REPORT",
            "TableConfigurations": {{
                "COST_AND_USAGE_REPORT": {{
                    "TIME_GRANULARITY": "HOURLY",
                    "INCLUDE_RESOURCES": "TRUE",
                    "INCLUDE_SPLIT_COST_ALLOCATION_DATA": "FALSE",
                    "INCLUDE_MANUAL_DISCOUNT_COMPATIBILITY": "FALSE",
                    "INCLUDE_CALLER_IDENTITY_DATA": "TRUE"
                }}
            }}
        }},
        "DestinationConfigurations": {{
            "S3Destination": {{
                "S3Bucket": "'"$CUR_BUCKET_NAME"'",
                "S3Prefix": "bedrock-cur2",
                "S3Region": "'"$CUR_BUCKET_REGION"'",
                "S3OutputConfigurations": {{
                    "OutputType": "CUSTOM",
                    "Format": "PARQUET",
                    "Compression": "PARQUET",
                    "Overwrite": "OVERWRITE_REPORT"
                }}
            }}
        }},
        "RefreshCadence": {{ "Frequency": "SYNCHRONOUS" }}
    }}'

echo
echo "Done. CUR 2.0 export will start populating on the next billing cycle."
echo "First IAM principal data should appear in 24-48 hours."

"""  # nosec B608 - not a SQL query: this f-string renders a bash setup script. The only SQL-looking token is the constant CUR 2.0 export DataQuery ("SELECT * FROM COST_AND_USAGE_REPORT"), a fixed AWS bcm-data-exports literal with no interpolation. The lone interpolated value ("suggested_bucket", an AWS account id) lands in a bash var, never in a query.


SCRIPT_FOOTER = """
# ════════════════════════════════════════════════════════════════════
# Done.
# ════════════════════════════════════════════════════════════════════
#
# What to expect:
#   - Section 1 changes are visible in the IAM console immediately.
#   - Section 2 activations are visible in Cost Allocation Tags within
#     a few minutes; cost data tagged with the new keys takes up to 24h
#     to flow into Cost Explorer.
#   - Section 3 export files start landing in S3 within 24h of creation.
#
# Run `bedrock-attribution-audit run` again in a few days and the
# 'Compared to last run' section will show your progress.
"""


def render_setup_script(
    findings: AccountFindings, suggestions: list[TagSuggestion]
) -> str:
    """Build the full setup-tier1.sh content as a string."""
    header = SCRIPT_HEADER_TEMPLATE.format(
        generated_at=datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z",
        account_id=findings.account_id,
        account_name=findings.account_name or "(no name)",
        audit_started_at=findings.audit_started_at,
    )
    return (
        header
        + _section_tag_iam_principals(findings, suggestions)
        + _section_activate_cost_allocation_tags(findings)
        + _section_create_cur_export(findings)
        + SCRIPT_FOOTER
    )


def write_setup_script(
    findings: AccountFindings,
    suggestions: list[TagSuggestion],
    output_dir: Path,
) -> tuple[Path, str]:
    """Write `setup-tier1.sh` to the output directory and chmod +x.

    Returns ``(path, content)`` so the caller can both confirm where the file
    landed AND embed the same content in other artifacts (e.g. the HTML
    report's Next-steps section) without regenerating it twice.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"setup-tier1-{findings.account_id}.sh"
    content = render_setup_script(findings, suggestions)
    path.write_text(content)
    path.chmod(0o755)
    return path, content
